config/routes.rb
Rails.application.routes.draw do
  get 'index' => 'static#index'
  get 'search' => 'static#search'
  get 'about' => 'static#about'

  get 'data_update' => 'static#update_data'

  resources :readings
  resources :readers
  resources :poems
  resources :poets
  resources :collections

  root 'static#index'

  get '/api/poems' => 'api/poems#index'

end

app/views/shared/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-17240533-16', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_live_filter.html.erb
<script>
  $(function() {
      $('#live-filter').fastLiveFilter('#search-results .item');
      // alert("test");
  });
</script>

app/views/shared/_meta.html.erb
  <title>Poetic Voices</title>

  <!-- OG Meta Data -->
  <meta content="Poetic Voices" property="og:title">
  <meta content="Audio and video readings of your favourite poems" property="og:description">
  <meta content="website" property="og:type">
  <meta content="http://www.poetic-voices.com/" property="og:url">
  <meta content="<%= asset_path('cover.jpg') %>" property="og:image">
  <meta content="Poetic Voices" property="og:site_name">
  <!-- Twitter -->
  <meta content="summary_large_image" name="twitter:card">
  <meta content="http://www.poetic-voices.com/" name="twitter:url">
  <meta content="Poetic Voices" name="twitter:title">
  <meta content="Audio and video readings of your favourite poems" name="twitter:description">
  <meta content="<%= asset_path('cover.jpg') %>" name="twitter:image">
  <meta content="@davemcginn_ie" name="twitter:site">

app/views/shared/_meta_collections.html.erb
  <title>Poetic Voices | Collection: <%= @collection.name %></title>

  <!-- OG Meta Data -->
  <meta content="Poetic Voices" property="og:title">
  <meta content="<%= @collection.name %> collection of poetry readings. Audio and video readings of your favourite poems" property="og:description">
  <meta content="website" property="og:type">
  <meta content="<%= collection_url(@collection) %>" property="og:url">
  <meta content="<%= @collection.cover_image %>" property="og:image">
  <meta content="Poetic Voices" property="og:site_name">
  <!-- Twitter -->
  <meta content="summary_large_image" name="twitter:card">
  <meta content="<%= collection_url(@collection) %>" name="twitter:url">
  <meta content="Poetic Voices" name="twitter:title">
  <meta content="<%= @collection.name %> collection of poetry readings. Audio and video readings of your favourite poems" name="twitter:description">
  <meta content="<%= @collection.cover_image %>" name="twitter:image">
  <meta content="@davemcginn_ie" name="twitter:site">

app/views/shared/_meta_poems.html.erb
  <title>Poetic Voices | <%= @poem.title %> by <%= @poem.poet.name %></title>

  <!-- OG Meta Data -->
  <meta content="Poetic Voices" property="og:title">
  <meta content="Audio and video readings of ‘<%= @poem.title %>’ by <%= @poem.poet.name %>" property="og:description">
  <meta content="website" property="og:type">
  <meta content="<%= poem_url(@poem) %>" property="og:url">
  <meta content="<%= asset_path('cover.jpg') %>" property="og:image">
  <meta content="Poetic Voices" property="og:site_name">
  <!-- Twitter -->
  <meta content="summary_large_image" name="twitter:card">
  <meta content="<%= poem_url(@poem) %>" name="twitter:url">
  <meta content="Poetic Voices" name="twitter:title">
  <meta content="Audio and video readings of ‘<%= @poem.title %>’ by <%= @poem.poet.name %>" name="twitter:description">
  <meta content="<%= asset_path('cover.jpg') %>" name="twitter:image">
  <meta content="@davemcginn_ie" name="twitter:site">

app/views/shared/_meta_poets.html.erb
  <title>Poetic Voices | Readings of <%= @poet.name %>'s poetry</title>

  <!-- OG Meta Data -->
  <meta content="Poetic Voices" property="og:title">
  <meta content="Audio and video readings of poems by <%= @poet.name %>" property="og:description">
  <meta content="website" property="og:type">
  <meta content="<%= poet_url(@poet) %>" property="og:url">
  <meta content="<%= @poet.image %>" property="og:image">
  <meta content="Poetic Voices" property="og:site_name">
  <!-- Twitter -->
  <meta content="summary_large_image" name="twitter:card">
  <meta content="<%= poet_url(@poet) %>" name="twitter:url">
  <meta content="Poetic Voices" name="twitter:title">
  <meta content="Audio and video readings of poems by <%= @poet.name %>" name="twitter:description">
  <meta content="<%= @poet.image %>" name="twitter:image">
  <meta content="@davemcginn_ie" name="twitter:site">

app/views/shared/_meta_readers.html.erb
  <title>Poetic Voices | Poetry readings by <%= @reader.name %></title>

  <!-- OG Meta Data -->
  <meta content="Poetic Voices" property="og:title">
  <meta content="Audio and video poetry readings by <%= @reader.name %>" property="og:description">
  <meta content="website" property="og:type">
  <meta content="<%= reader_url(@reader) %>" property="og:url">
  <meta content="<%= @reader.image %>" property="og:image">
  <meta content="Poetic Voices" property="og:site_name">
  <!-- Twitter -->
  <meta content="summary_large_image" name="twitter:card">
  <meta content="<%= reader_url(@reader) %>" name="twitter:url">
  <meta content="Poetic Voices" name="twitter:title">
  <meta content="Audio and video poetry readings by <%= @reader.name %>" name="twitter:description">
  <meta content="<%= @reader.image %>" name="twitter:image">
  <meta content="@davemcginn_ie" name="twitter:site">