config/routes.rb
Rails.application.routes.draw do
  get 'index' => 'static#index'
  get 'search' => 'static#search'
  get 'about' => 'static#about'

  get 'data_update' => 'static#update_data'

  resources :readings
  resources :readers
  resources :poems
  resources :poets
  resources :collections

  root 'static#index'

  get '/api/poems' => 'api/poems#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'jquery.fastLiveFilter', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <% 
  variable_name = params[:controller][0..-2]
  %>

  <% if params[:action]=='show' %>
    <%= render "shared/meta_#{params[:controller]}", variable_name.to_sym => instance_variable_get("@#{variable_name}") %>
  <% else %>
    <%= render "shared/meta" %>
  <% end %>

</head>
<body class="welcome">
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation-bar" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">
        Poetic Voices
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navigation-bar">
        <ul class="nav navbar-nav">
          <li><%= link_to "Poets", poets_path %></li>
          <li><%= link_to "Poems", poems_path %></li>
          <li><%= link_to "Readers", readers_path %></li>
        </ul>
        <form class="navbar-form" action="/search" method="GET">
          <div class="form-group">
            <input type="text" name="q" placeholder="Search..." class="form-control">
          </div>
        </form>
      </div>


    </div>
  </nav>


  <div>
    <div class="container">
      <!-- <div class="row"> -->
        <!-- <div class="col-md-12"> -->


          <%= yield %>

        <!-- </div> -->
      <!-- </div> -->
    </div>
  </div>


  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
        <!-- <hr> -->
          <br /> <br />
          <ul class="list-inline pull-right">
            <!-- <li class="text-muted"><%= link_to "About", controller: 'static', action: 'about' %></li>
            <li class="text-muted"><a target="_blank" href="https://twitter.com/davemcginn_ie">Twitter</a></li> -->
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <!-- /Footer -->

  <%= render "shared/google_analytics" %>

</body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <%= render "shared/meta" %>

</head>
<body class="welcome">
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation-bar" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">
        Poetic Voices
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navigation-bar">
        <ul class="nav navbar-nav">
          <li><%= link_to "Poets", poets_path %></li>
          <li><%= link_to "Poems", poems_path %></li>
          <li><%= link_to "Readers", readers_path %></li>
        </ul>
<!--         <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About", controller: 'static', action: 'about' %></li>
        </ul> -->
      </div>
    </div>
  </nav>


  <div class="homepage">
    <div class="container">
      <div class="row billboard">
        <div class="col-md-8 col-md-offset-2">
          <h1>Poetic Voices</h1>
          <p class="lead">Audio and video readings of your favourite poems</p>
          <%= form_tag('/search', method: 'get') do %>
            <div class="input-group" id="form-search-group">
              <%= text_field_tag 'q', nil, id: "form-input", placeholder:"Search for a poet, a poem or a reader", class:"form-control" %>
              <span class="input-group-btn">
                <%= button_tag "Search", type: 'button', id: 'form-submit', class: 'btn btn-primary btn-search' %>
              </span>
            </div>

          <% end %>
          
          <p class="lead">Or browse <%= link_to "Poets", controller: "poets", action: "index" %>, <%= link_to "Poems", controller: "poems", action: "index" %>, or <%= link_to "Readers", controller: "readers", action: "index" %></p>

        </div>
      </div>
    </div>
  </div>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="col-sm-6 item">
            <h3>Latest Readings</h3>
            <div class="thumbnail">
              <!-- <div class="caption"> -->
              <!-- <ul class="list-unstyled"> -->
                <% @latest_readings.each do |reading| %>
                  <h4 style="font-weight: normal; line-height: 1.3em;"><%= link_to "&lsquo;#{reading.poem.title}&rsquo;".html_safe, poem_path(reading.poem) %> read by <%= link_to reading.reader.name, reader_path(reading.reader) %></h4>
                  <!-- <li><em>2 days ago</em>&nbsp;<%= link_to "&lsquo;#{reading.poem.title}&rsquo;".html_safe, poem_path(reading.poem) %> read by <%= link_to reading.reader.name, reader_path(reading.reader) %></li> -->
                <% end %>
              <!-- </ul> -->
              <!-- </div> -->
            </div>
          </div>

          <div class="col-sm-3 item">
            <h3>Featured Poet</h3>
            <div class="thumbnail">
              <div class="caption">
                <h4><%= @featured_poet.name %></h4>
                <img src="<%= @featured_poet.image %>" style="max-width:100%;" />
                <h4 class="text-center"><%= link_to "#{@featured_poet.poems.count} poems", poet_path(@featured_poet) %></h4>
              </div>
            </div>
          </div>

          <div class="col-sm-3 item">
            <h3>Featured Reader</h3>
            <div class="thumbnail">
              <div class="caption">
                <h4><%= @featured_reader.name %></h4>
                <img src="<%= @featured_reader.image %>" style="max-width:100%;" />
                <h4 class="text-center"><%= link_to "#{@featured_reader.readings.count} readings", reader_path(@featured_reader) %></h4>
              </div>
            </div>
          </div>

        </div>

      </div>
    </div>
  </footer>
  <!-- /Footer -->

  <%= render "shared/google_analytics" %>

</body>
</html>